__merge__: ../../api/comp_control_method.yaml

name: random_labels
label: Random Labels
summary: Randomly assigned labels.
description: |
  Randomly assign a label to each cell from the labels present in the training
  data

info:
  preferred_normalization: log_cp10k

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
